OpenVPN client

diff --git a/package/openvpn/files/openvpn-client.init b/package/openvpn/files/openvpn-client.init
--- a/package/openvpn/files/openvpn-client.init
+++ b/package/openvpn/files/openvpn-client.init
@@ -11,25 +11,6 @@ EXTENDER_MODE=$($CONFIG get extender_mode)
 OPENVPN_CONF_DIR=/etc/openvpn/config/client
 
 start() {
-	# Check if OpenVPN server is enabled
-	if [ "$($CONFIG get vpn_enable)" = "1" ]; then
-		echo "Error: OpenVPN server is enabled. Disable it to start OpenVPN client."
-		exit 1
-	fi
-
-	# Check if not router mode
-	if [ "$AP_MODE" == "1" ] || [ "$BRIDGE_MODE" == "1" ] || [ "$EXTENDER_MODE" == "1" ]; then
-		echo "Error: Not router mode."
-		exit 1
-	fi
-
-	# Check if tun0 interface already exists
-	ifconfig | grep -q tun0
-	if [ $? -eq 0 ]; then
-		echo "Error: tun0 interface exists. OpenVPN client is probably already started."
-		exit 1
-	fi
-
 	# Check existence of /etc/openvpn/config/client/*.ovpn file
 	OVPN_CLIENT_CONF=0
 	for OVPN in $OPENVPN_CONF_DIR/*.ovpn; do
@@ -45,14 +26,40 @@ start() {
 		exit 1;
 	fi
 
+	# Check if not router mode
+	if [ "$AP_MODE" == "1" ] || [ "$BRIDGE_MODE" == "1" ] || [ "$EXTENDER_MODE" == "1" ]; then
+		echo "Error: Not router mode."
+		echo "Error: Not router mode." >> $LOG_FILE
+		exit 1
+	fi
+
+	# Check if OpenVPN server is enabled
+	if [ "$($CONFIG get vpn_enable)" = "1" ]; then
+		echo "Error: OpenVPN server is enabled. Disable it to start OpenVPN client."
+		echo "Error: OpenVPN server is enabled. Disable it to start OpenVPN client." >> $LOG_FILE
+		/sbin/ledcontrol -n wan -c red -s on
+		exit 1
+	fi
+
+	# Check if tun0 interface already exists
+	ifconfig | grep -q tun0
+	if [ $? -eq 0 ]; then
+		echo "Error: tun0 interface exists. OpenVPN client is probably already started."
+		echo "Error: tun0 interface exists. OpenVPN client is probably already started." >> $LOG_FILE
+		exit 1
+	fi
+
 	# Start OpenVPN client
-	$PROG --writepid $PID_FILE --log-append $LOG_FILE --config $OVPN_CLIENT_CONF --daemon
+	$PROG --writepid $PID_FILE --log-append $LOG_FILE --config $OVPN_CLIENT_CONF --script-security 2 --up /etc/openvpn/ovpnclient-up.sh --down /etc/openvpn/ovpnclient-down.sh --daemon
 	echo "Please wait..."
 	sleep 20
 	ifconfig | grep -q tun0
 	if [ $? -ne 0 ]; then
 		echo "Error: OpenVPN client start failed."
+		echo "Error: OpenVPN client start failed." >> $LOG_FILE
+		/sbin/ledcontrol -n wan -c red -s on
 		if [ -f $PID_FILE ]; then
+			kill `cat $PID_FILE` 
 			rm -f $PID_FILE
 		fi
 		exit 1
@@ -64,8 +71,8 @@ start() {
 }
 
 stop() {
-	kill `cat $PID_FILE` 
 	if [ -f $PID_FILE ]; then
+		kill `cat $PID_FILE` 
 		rm -f $PID_FILE
 	fi
 
